export enum CityName {
  Taipei = 'Taipei',
  NewTaipei = 'NewTaipei',
  Taoyuan = 'Taoyuan',
  Taichung = 'Taichung',
  Tainan = 'Tainan',
  Kaohsiung = 'Kaohsiung',
  Keelung = 'Keelung',
  Hsinchu = 'Hsinchu',
  HsinchuCounty = 'HsinchuCounty',
  MiaoliCounty = 'MiaoliCounty',
  ChanghuaCounty = 'ChanghuaCounty',
  NaotouCounty = 'NaotouCounty',
  YunlinCounty = 'YunlinCounty',
  ChiayiCounty = 'ChiayiCounty',
  Chiayi = 'Chiayi',
  PingtungCounty = 'PingtungCounty',
  YilanCounty = 'YilanCounty',
  HualienCounty = 'HualienCounty',
  TaitungCounty = 'TaitungCounty',
  KinmenCounty = 'KinmenCounty',
  PenghuCounty = 'PenghuCounty',
  LienchiangCounty = 'LienchiangCounty',
}
